// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urgqkhmasmedgshizrxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZ3FraG1hc21lZGdzaGl6cnhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMDYxNDYsImV4cCI6MjA1NzY4MjE0Nn0.1hVhyLN-CN4pOPrDLQqPB2DACdz7AH7QzDvHtA7Lo7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);